version: "1"
services:
  app:
    build: .
    depends_on: 
      - db
    entrypoint: mvn exec:java
    volumes:
      - m2:/root/.m2
  db:
    image: mysql    
    ports: 
      - '3306:3306'
    expose: 
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'customerdb'
      MYSQL_PORT: '3306'
    volumes:
      - my-db:/var/lib/mysql

# Names our volume
volumes:
  my-db:
  m2:
